library(magrittr)
library(raster)
library(sp)
library(tigris)
library(lubridate)
library(zoo)
library(tidyverse)
library(maps)
library(RColorBrewer)
library(broom)
library(knitr)
library(kableExtra)
library(mgcv)
library(spdep)
library(rspatial)    # devtools::install_github('rspatial/rspatial')

